(setq *fake-register* nil)
(setq *register-name* ?\0)
(setq maximum-registers 8)
(defun push-register ()
  (interactive)
  (when (> (length *fake-register*)  maximum-registers)
    (setq *fake-register* (butlast *fake-register*)))
  (when (> *register-name*  ?\8)
    (setq *register-name* 0))
  (push *register-name* *fake-register*)
  (point-to-register *register-name*)
  (incf *register-name*)
  (message "pushed current position to register."))
(defun pop-register ()
  (interactive)
  (when *fake-register*
    (setq rname (pop *fake-register*))
    (jump-to-register rname))
  (message "popped register."))
(provide 'bunny-register-jumper)
